name: Docker Build a PR

on:
  push:
    branches:
    - '!main'
  pull_request:
    branches:
    - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Docker Build & Push, Kubectl apply
      run: |
        docker build --tag levelupdevops-pr:${{ github.sha }} .
